// Code generated by goctl. DO NOT EDIT.
// Source: distribute.proto

package server

import (
	"context"

	"dist-encoder/app/manager/internal/logic"
	"dist-encoder/app/manager/internal/svc"
	"dist-encoder/pb/distribute"
)

type DistributeServer struct {
	svcCtx *svc.ServiceContext
	distribute.UnimplementedDistributeServer
}

func NewDistributeServer(svcCtx *svc.ServiceContext) *DistributeServer {
	return &DistributeServer{
		svcCtx: svcCtx,
	}
}

// 工作机器获取工作任务
func (s *DistributeServer) GetVideoJob(ctx context.Context, in *distribute.GetVideoJobRequest) (*distribute.GetVideoJobResponse, error) {
	l := logic.NewGetVideoJobLogic(ctx, s.svcCtx)
	return l.GetVideoJob(in)
}

// 工作机器上报工作状态
func (s *DistributeServer) SetVideoJobResult(ctx context.Context, in *distribute.SetVideoJobResultRequest) (*distribute.SetVideoJobResultResponse, error) {
	l := logic.NewSetVideoJobResultLogic(ctx, s.svcCtx)
	return l.SetVideoJobResult(in)
}

// QueryVideoJob 查询转码任务
func (s *DistributeServer) QueryVideoJob(ctx context.Context, in *distribute.QueryVideoJobRequest) (*distribute.QueryVideoJobResponse, error) {
	l := logic.NewQueryVideoJobLogic(ctx, s.svcCtx)
	return l.QueryVideoJob(in)
}

// AddVideoJob 添加视频转码任务
func (s *DistributeServer) AddVideoJob(ctx context.Context, in *distribute.AddVideoJobRequest) (*distribute.AddVideoJobResponse, error) {
	l := logic.NewAddVideoJobLogic(ctx, s.svcCtx)
	return l.AddVideoJob(in)
}

// ListConvertCnf 查询转码任务
func (s *DistributeServer) ListConvertCnf(ctx context.Context, in *distribute.ListConvertCnfRequest) (*distribute.ListConvertCnfResponse, error) {
	l := logic.NewListConvertCnfLogic(ctx, s.svcCtx)
	return l.ListConvertCnf(in)
}

// AddConvertCnf 添加视频转码任务
func (s *DistributeServer) AddConvertCnf(ctx context.Context, in *distribute.AddConvertCnfRequest) (*distribute.AddConvertCnfResponse, error) {
	l := logic.NewAddConvertCnfLogic(ctx, s.svcCtx)
	return l.AddConvertCnf(in)
}
