// Code generated by goctl. DO NOT EDIT.
// Source: manager.proto

package server

import (
	"context"

	"dist-encoder/app/manager/internal/logic"
	"dist-encoder/app/manager/internal/svc"
	"dist-encoder/pb/manager"
)

type ManagerServer struct {
	svcCtx *svc.ServiceContext
	manager.UnimplementedManagerServer
}

func NewManagerServer(svcCtx *svc.ServiceContext) *ManagerServer {
	return &ManagerServer{
		svcCtx: svcCtx,
	}
}

func (s *ManagerServer) GetVideoJob(ctx context.Context, in *manager.Worker) (*manager.VideoJob, error) {
	l := logic.NewGetVideoJobLogic(ctx, s.svcCtx)
	return l.GetVideoJob(in)
}
