// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: distribute.proto

package distribute

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 任务状态
type Status int32

const (
	Status_Failed  Status = 0
	Status_Success Status = 1
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "Failed",
		1: "Success",
	}
	Status_value = map[string]int32{
		"Failed":  0,
		"Success": 1,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_distribute_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_distribute_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_distribute_proto_rawDescGZIP(), []int{0}
}

// GetVideoJob 工作机器获取工作任务
type GetVideoJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Ip   string `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *GetVideoJobRequest) Reset() {
	*x = GetVideoJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distribute_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVideoJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoJobRequest) ProtoMessage() {}

func (x *GetVideoJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distribute_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoJobRequest.ProtoReflect.Descriptor instead.
func (*GetVideoJobRequest) Descriptor() ([]byte, []int) {
	return file_distribute_proto_rawDescGZIP(), []int{0}
}

func (x *GetVideoJobRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *GetVideoJobRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

// GetVideoJob 工作机器获取工作任务
type GetVideoJobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Job        *VideoJob   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	ConvertCnf *ConvertCnf `protobuf:"bytes,2,opt,name=convert_cnf,json=convertCnf,proto3" json:"convert_cnf,omitempty"`
}

func (x *GetVideoJobResponse) Reset() {
	*x = GetVideoJobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distribute_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVideoJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoJobResponse) ProtoMessage() {}

func (x *GetVideoJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distribute_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoJobResponse.ProtoReflect.Descriptor instead.
func (*GetVideoJobResponse) Descriptor() ([]byte, []int) {
	return file_distribute_proto_rawDescGZIP(), []int{1}
}

func (x *GetVideoJobResponse) GetJob() *VideoJob {
	if x != nil {
		return x.Job
	}
	return nil
}

func (x *GetVideoJobResponse) GetConvertCnf() *ConvertCnf {
	if x != nil {
		return x.ConvertCnf
	}
	return nil
}

// SetVideoJobResult 工作机器上报工作状态
type SetVideoJobResultRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId  int64  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status Status `protobuf:"varint,2,opt,name=status,proto3,enum=distribute.Status" json:"status,omitempty"`
}

func (x *SetVideoJobResultRequest) Reset() {
	*x = SetVideoJobResultRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distribute_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetVideoJobResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVideoJobResultRequest) ProtoMessage() {}

func (x *SetVideoJobResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distribute_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVideoJobResultRequest.ProtoReflect.Descriptor instead.
func (*SetVideoJobResultRequest) Descriptor() ([]byte, []int) {
	return file_distribute_proto_rawDescGZIP(), []int{2}
}

func (x *SetVideoJobResultRequest) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *SetVideoJobResultRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_Failed
}

// SetVideoJobResult 工作机器上报工作状态
type SetVideoJobResultResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetVideoJobResultResponse) Reset() {
	*x = SetVideoJobResultResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distribute_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetVideoJobResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVideoJobResultResponse) ProtoMessage() {}

func (x *SetVideoJobResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distribute_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVideoJobResultResponse.ProtoReflect.Descriptor instead.
func (*SetVideoJobResultResponse) Descriptor() ([]byte, []int) {
	return file_distribute_proto_rawDescGZIP(), []int{3}
}

type VideoJob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId     int64  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	InPut     string `protobuf:"bytes,2,opt,name=in_put,json=inPut,proto3" json:"in_put,omitempty"`
	OutPut    string `protobuf:"bytes,3,opt,name=out_put,json=outPut,proto3" json:"out_put,omitempty"`
	ConvertId int64  `protobuf:"varint,4,opt,name=convert_id,json=convertId,proto3" json:"convert_id,omitempty"`
	Status    Status `protobuf:"varint,5,opt,name=status,proto3,enum=distribute.Status" json:"status,omitempty"`
}

func (x *VideoJob) Reset() {
	*x = VideoJob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distribute_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoJob) ProtoMessage() {}

func (x *VideoJob) ProtoReflect() protoreflect.Message {
	mi := &file_distribute_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoJob.ProtoReflect.Descriptor instead.
func (*VideoJob) Descriptor() ([]byte, []int) {
	return file_distribute_proto_rawDescGZIP(), []int{4}
}

func (x *VideoJob) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *VideoJob) GetInPut() string {
	if x != nil {
		return x.InPut
	}
	return ""
}

func (x *VideoJob) GetOutPut() string {
	if x != nil {
		return x.OutPut
	}
	return ""
}

func (x *VideoJob) GetConvertId() int64 {
	if x != nil {
		return x.ConvertId
	}
	return 0
}

func (x *VideoJob) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_Failed
}

type ConvertCnf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CnfId     int64     `protobuf:"varint,1,opt,name=cnf_id,json=cnfId,proto3" json:"cnf_id,omitempty"`
	InKwArgs  []*KwArgs `protobuf:"bytes,2,rep,name=in_kw_args,json=inKwArgs,proto3" json:"in_kw_args,omitempty"`
	OutKwArgs []*KwArgs `protobuf:"bytes,3,rep,name=out_kw_args,json=outKwArgs,proto3" json:"out_kw_args,omitempty"`
}

func (x *ConvertCnf) Reset() {
	*x = ConvertCnf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distribute_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConvertCnf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertCnf) ProtoMessage() {}

func (x *ConvertCnf) ProtoReflect() protoreflect.Message {
	mi := &file_distribute_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertCnf.ProtoReflect.Descriptor instead.
func (*ConvertCnf) Descriptor() ([]byte, []int) {
	return file_distribute_proto_rawDescGZIP(), []int{5}
}

func (x *ConvertCnf) GetCnfId() int64 {
	if x != nil {
		return x.CnfId
	}
	return 0
}

func (x *ConvertCnf) GetInKwArgs() []*KwArgs {
	if x != nil {
		return x.InKwArgs
	}
	return nil
}

func (x *ConvertCnf) GetOutKwArgs() []*KwArgs {
	if x != nil {
		return x.OutKwArgs
	}
	return nil
}

// KwArgs 输出参数
type KwArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *KwArgs) Reset() {
	*x = KwArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distribute_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KwArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KwArgs) ProtoMessage() {}

func (x *KwArgs) ProtoReflect() protoreflect.Message {
	mi := &file_distribute_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KwArgs.ProtoReflect.Descriptor instead.
func (*KwArgs) Descriptor() ([]byte, []int) {
	return file_distribute_proto_rawDescGZIP(), []int{6}
}

func (x *KwArgs) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KwArgs) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Page struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderBy string `protobuf:"bytes,1,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Order   string `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	Offset  int64  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit   int64  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *Page) Reset() {
	*x = Page{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distribute_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_distribute_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_distribute_proto_rawDescGZIP(), []int{7}
}

func (x *Page) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *Page) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *Page) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Page) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// QueryVideoJob 查询转码任务
type QueryVideoJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page *Page `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *QueryVideoJobRequest) Reset() {
	*x = QueryVideoJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distribute_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryVideoJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryVideoJobRequest) ProtoMessage() {}

func (x *QueryVideoJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distribute_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryVideoJobRequest.ProtoReflect.Descriptor instead.
func (*QueryVideoJobRequest) Descriptor() ([]byte, []int) {
	return file_distribute_proto_rawDescGZIP(), []int{8}
}

func (x *QueryVideoJobRequest) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

type QueryVideoJobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page *Page       `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	Jobs []*VideoJob `protobuf:"bytes,2,rep,name=jobs,proto3" json:"jobs,omitempty"`
}

func (x *QueryVideoJobResponse) Reset() {
	*x = QueryVideoJobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distribute_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryVideoJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryVideoJobResponse) ProtoMessage() {}

func (x *QueryVideoJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distribute_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryVideoJobResponse.ProtoReflect.Descriptor instead.
func (*QueryVideoJobResponse) Descriptor() ([]byte, []int) {
	return file_distribute_proto_rawDescGZIP(), []int{9}
}

func (x *QueryVideoJobResponse) GetPage() *Page {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *QueryVideoJobResponse) GetJobs() []*VideoJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

// AddVideoJob 添加视频转码任务
type AddVideoJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InPut     string `protobuf:"bytes,2,opt,name=in_put,json=inPut,proto3" json:"in_put,omitempty"`
	OutPut    string `protobuf:"bytes,3,opt,name=out_put,json=outPut,proto3" json:"out_put,omitempty"`
	ConvertId int64  `protobuf:"varint,4,opt,name=convert_id,json=convertId,proto3" json:"convert_id,omitempty"`
}

func (x *AddVideoJobRequest) Reset() {
	*x = AddVideoJobRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distribute_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddVideoJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVideoJobRequest) ProtoMessage() {}

func (x *AddVideoJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distribute_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVideoJobRequest.ProtoReflect.Descriptor instead.
func (*AddVideoJobRequest) Descriptor() ([]byte, []int) {
	return file_distribute_proto_rawDescGZIP(), []int{10}
}

func (x *AddVideoJobRequest) GetInPut() string {
	if x != nil {
		return x.InPut
	}
	return ""
}

func (x *AddVideoJobRequest) GetOutPut() string {
	if x != nil {
		return x.OutPut
	}
	return ""
}

func (x *AddVideoJobRequest) GetConvertId() int64 {
	if x != nil {
		return x.ConvertId
	}
	return 0
}

type AddVideoJobResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId int64 `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
}

func (x *AddVideoJobResponse) Reset() {
	*x = AddVideoJobResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distribute_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddVideoJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVideoJobResponse) ProtoMessage() {}

func (x *AddVideoJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distribute_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVideoJobResponse.ProtoReflect.Descriptor instead.
func (*AddVideoJobResponse) Descriptor() ([]byte, []int) {
	return file_distribute_proto_rawDescGZIP(), []int{11}
}

func (x *AddVideoJobResponse) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

// ListConvertCnf 查询转码任务
type ListConvertCnfRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListConvertCnfRequest) Reset() {
	*x = ListConvertCnfRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distribute_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListConvertCnfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConvertCnfRequest) ProtoMessage() {}

func (x *ListConvertCnfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distribute_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConvertCnfRequest.ProtoReflect.Descriptor instead.
func (*ListConvertCnfRequest) Descriptor() ([]byte, []int) {
	return file_distribute_proto_rawDescGZIP(), []int{12}
}

type ListConvertCnfResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Converts []*ConvertCnf `protobuf:"bytes,1,rep,name=converts,proto3" json:"converts,omitempty"`
}

func (x *ListConvertCnfResponse) Reset() {
	*x = ListConvertCnfResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distribute_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListConvertCnfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConvertCnfResponse) ProtoMessage() {}

func (x *ListConvertCnfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distribute_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConvertCnfResponse.ProtoReflect.Descriptor instead.
func (*ListConvertCnfResponse) Descriptor() ([]byte, []int) {
	return file_distribute_proto_rawDescGZIP(), []int{13}
}

func (x *ListConvertCnfResponse) GetConverts() []*ConvertCnf {
	if x != nil {
		return x.Converts
	}
	return nil
}

// AddConvertCnf 添加视频转码任务
type AddConvertCnfRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InKwArgs  []*KwArgs `protobuf:"bytes,2,rep,name=in_kw_args,json=inKwArgs,proto3" json:"in_kw_args,omitempty"`
	OutKwArgs []*KwArgs `protobuf:"bytes,3,rep,name=out_kw_args,json=outKwArgs,proto3" json:"out_kw_args,omitempty"`
}

func (x *AddConvertCnfRequest) Reset() {
	*x = AddConvertCnfRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distribute_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddConvertCnfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddConvertCnfRequest) ProtoMessage() {}

func (x *AddConvertCnfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distribute_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddConvertCnfRequest.ProtoReflect.Descriptor instead.
func (*AddConvertCnfRequest) Descriptor() ([]byte, []int) {
	return file_distribute_proto_rawDescGZIP(), []int{14}
}

func (x *AddConvertCnfRequest) GetInKwArgs() []*KwArgs {
	if x != nil {
		return x.InKwArgs
	}
	return nil
}

func (x *AddConvertCnfRequest) GetOutKwArgs() []*KwArgs {
	if x != nil {
		return x.OutKwArgs
	}
	return nil
}

type AddConvertCnfResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CnfId int64 `protobuf:"varint,1,opt,name=cnf_id,json=cnfId,proto3" json:"cnf_id,omitempty"`
}

func (x *AddConvertCnfResponse) Reset() {
	*x = AddConvertCnfResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_distribute_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddConvertCnfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddConvertCnfResponse) ProtoMessage() {}

func (x *AddConvertCnfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distribute_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddConvertCnfResponse.ProtoReflect.Descriptor instead.
func (*AddConvertCnfResponse) Descriptor() ([]byte, []int) {
	return file_distribute_proto_rawDescGZIP(), []int{15}
}

func (x *AddConvertCnfResponse) GetCnfId() int64 {
	if x != nil {
		return x.CnfId
	}
	return 0
}

var File_distribute_proto protoreflect.FileDescriptor

var file_distribute_proto_rawDesc = []byte{
	0x0a, 0x10, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x22, 0x38,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x22, 0x76, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x26, 0x0a, 0x03, 0x6a, 0x6f, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4a,
	0x6f, 0x62, 0x52, 0x03, 0x6a, 0x6f, 0x62, 0x12, 0x37, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x76, 0x65,
	0x72, 0x74, 0x5f, 0x63, 0x6e, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72,
	0x74, 0x43, 0x6e, 0x66, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x43, 0x6e, 0x66,
	0x22, 0x5d, 0x0a, 0x18, 0x53, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4a, 0x6f, 0x62, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06,
	0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6a, 0x6f,
	0x62, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x1b, 0x0a, 0x19, 0x53, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4a, 0x6f, 0x62, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x9c, 0x01, 0x0a,
	0x08, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4a, 0x6f, 0x62, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64,
	0x12, 0x15, 0x0a, 0x06, 0x69, 0x6e, 0x5f, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x69, 0x6e, 0x50, 0x75, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6f, 0x75, 0x74, 0x5f, 0x70,
	0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x50, 0x75, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x49, 0x64, 0x12,
	0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x12, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x89, 0x01, 0x0a, 0x0a,
	0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x43, 0x6e, 0x66, 0x12, 0x15, 0x0a, 0x06, 0x63, 0x6e,
	0x66, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6e, 0x66, 0x49,
	0x64, 0x12, 0x30, 0x0a, 0x0a, 0x69, 0x6e, 0x5f, 0x6b, 0x77, 0x5f, 0x61, 0x72, 0x67, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x2e, 0x4b, 0x77, 0x41, 0x72, 0x67, 0x73, 0x52, 0x08, 0x69, 0x6e, 0x4b, 0x77, 0x41,
	0x72, 0x67, 0x73, 0x12, 0x32, 0x0a, 0x0b, 0x6f, 0x75, 0x74, 0x5f, 0x6b, 0x77, 0x5f, 0x61, 0x72,
	0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x2e, 0x4b, 0x77, 0x41, 0x72, 0x67, 0x73, 0x52, 0x09, 0x6f, 0x75,
	0x74, 0x4b, 0x77, 0x41, 0x72, 0x67, 0x73, 0x22, 0x30, 0x0a, 0x06, 0x4b, 0x77, 0x41, 0x72, 0x67,
	0x73, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x65, 0x0a, 0x04, 0x50, 0x61, 0x67,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x62, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x22, 0x3c, 0x0a, 0x14, 0x51, 0x75, 0x65, 0x72, 0x79, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4a, 0x6f,
	0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x67,
	0x0a, 0x15, 0x51, 0x75, 0x65, 0x72, 0x79, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4a, 0x6f, 0x62, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x28, 0x0a,
	0x04, 0x6a, 0x6f, 0x62, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x69,
	0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x2e, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4a, 0x6f,
	0x62, 0x52, 0x04, 0x6a, 0x6f, 0x62, 0x73, 0x22, 0x63, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a,
	0x06, 0x69, 0x6e, 0x5f, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69,
	0x6e, 0x50, 0x75, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6f, 0x75, 0x74, 0x5f, 0x70, 0x75, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x50, 0x75, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x13,
	0x41, 0x64, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x6a, 0x6f, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x4c, 0x69,
	0x73, 0x74, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x43, 0x6e, 0x66, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x4c, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x76, 0x65,
	0x72, 0x74, 0x43, 0x6e, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a,
	0x08, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x2e, 0x43, 0x6f, 0x6e,
	0x76, 0x65, 0x72, 0x74, 0x43, 0x6e, 0x66, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74,
	0x73, 0x22, 0x7c, 0x0a, 0x14, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x43,
	0x6e, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x0a, 0x69, 0x6e, 0x5f,
	0x6b, 0x77, 0x5f, 0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x2e, 0x4b, 0x77, 0x41, 0x72, 0x67,
	0x73, 0x52, 0x08, 0x69, 0x6e, 0x4b, 0x77, 0x41, 0x72, 0x67, 0x73, 0x12, 0x32, 0x0a, 0x0b, 0x6f,
	0x75, 0x74, 0x5f, 0x6b, 0x77, 0x5f, 0x61, 0x72, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x2e, 0x4b, 0x77,
	0x41, 0x72, 0x67, 0x73, 0x52, 0x09, 0x6f, 0x75, 0x74, 0x4b, 0x77, 0x41, 0x72, 0x67, 0x73, 0x22,
	0x2e, 0x0a, 0x15, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x43, 0x6e, 0x66,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x63, 0x6e, 0x66, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6e, 0x66, 0x49, 0x64, 0x2a,
	0x21, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x61, 0x69,
	0x6c, 0x65, 0x64, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x10, 0x01, 0x32, 0x9f, 0x04, 0x0a, 0x0a, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x12, 0x50, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4a, 0x6f, 0x62,
	0x12, 0x1e, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x2e, 0x47, 0x65,
	0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1f, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x2e, 0x47, 0x65,
	0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x62, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4a,
	0x6f, 0x62, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x24, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4a, 0x6f,
	0x62, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25,
	0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x56, 0x0a, 0x0d, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x4a, 0x6f, 0x62, 0x12, 0x20, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x64, 0x69, 0x73,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x50, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4a, 0x6f, 0x62, 0x12, 0x1e,
	0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f,
	0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x56,
	0x69, 0x64, 0x65, 0x6f, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x59, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74,
	0x43, 0x6e, 0x66, 0x12, 0x21, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x43, 0x6e, 0x66, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x43,
	0x6e, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x56, 0x0a, 0x0d,
	0x41, 0x64, 0x64, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x43, 0x6e, 0x66, 0x12, 0x20, 0x2e,
	0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x6f,
	0x6e, 0x76, 0x65, 0x72, 0x74, 0x43, 0x6e, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x21, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x2e, 0x41, 0x64, 0x64,
	0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x43, 0x6e, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_distribute_proto_rawDescOnce sync.Once
	file_distribute_proto_rawDescData = file_distribute_proto_rawDesc
)

func file_distribute_proto_rawDescGZIP() []byte {
	file_distribute_proto_rawDescOnce.Do(func() {
		file_distribute_proto_rawDescData = protoimpl.X.CompressGZIP(file_distribute_proto_rawDescData)
	})
	return file_distribute_proto_rawDescData
}

var file_distribute_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_distribute_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_distribute_proto_goTypes = []interface{}{
	(Status)(0),                       // 0: distribute.Status
	(*GetVideoJobRequest)(nil),        // 1: distribute.GetVideoJobRequest
	(*GetVideoJobResponse)(nil),       // 2: distribute.GetVideoJobResponse
	(*SetVideoJobResultRequest)(nil),  // 3: distribute.SetVideoJobResultRequest
	(*SetVideoJobResultResponse)(nil), // 4: distribute.SetVideoJobResultResponse
	(*VideoJob)(nil),                  // 5: distribute.VideoJob
	(*ConvertCnf)(nil),                // 6: distribute.ConvertCnf
	(*KwArgs)(nil),                    // 7: distribute.KwArgs
	(*Page)(nil),                      // 8: distribute.Page
	(*QueryVideoJobRequest)(nil),      // 9: distribute.QueryVideoJobRequest
	(*QueryVideoJobResponse)(nil),     // 10: distribute.QueryVideoJobResponse
	(*AddVideoJobRequest)(nil),        // 11: distribute.AddVideoJobRequest
	(*AddVideoJobResponse)(nil),       // 12: distribute.AddVideoJobResponse
	(*ListConvertCnfRequest)(nil),     // 13: distribute.ListConvertCnfRequest
	(*ListConvertCnfResponse)(nil),    // 14: distribute.ListConvertCnfResponse
	(*AddConvertCnfRequest)(nil),      // 15: distribute.AddConvertCnfRequest
	(*AddConvertCnfResponse)(nil),     // 16: distribute.AddConvertCnfResponse
}
var file_distribute_proto_depIdxs = []int32{
	5,  // 0: distribute.GetVideoJobResponse.job:type_name -> distribute.VideoJob
	6,  // 1: distribute.GetVideoJobResponse.convert_cnf:type_name -> distribute.ConvertCnf
	0,  // 2: distribute.SetVideoJobResultRequest.status:type_name -> distribute.Status
	0,  // 3: distribute.VideoJob.status:type_name -> distribute.Status
	7,  // 4: distribute.ConvertCnf.in_kw_args:type_name -> distribute.KwArgs
	7,  // 5: distribute.ConvertCnf.out_kw_args:type_name -> distribute.KwArgs
	8,  // 6: distribute.QueryVideoJobRequest.page:type_name -> distribute.Page
	8,  // 7: distribute.QueryVideoJobResponse.page:type_name -> distribute.Page
	5,  // 8: distribute.QueryVideoJobResponse.jobs:type_name -> distribute.VideoJob
	6,  // 9: distribute.ListConvertCnfResponse.converts:type_name -> distribute.ConvertCnf
	7,  // 10: distribute.AddConvertCnfRequest.in_kw_args:type_name -> distribute.KwArgs
	7,  // 11: distribute.AddConvertCnfRequest.out_kw_args:type_name -> distribute.KwArgs
	1,  // 12: distribute.Distribute.GetVideoJob:input_type -> distribute.GetVideoJobRequest
	3,  // 13: distribute.Distribute.SetVideoJobResult:input_type -> distribute.SetVideoJobResultRequest
	9,  // 14: distribute.Distribute.QueryVideoJob:input_type -> distribute.QueryVideoJobRequest
	11, // 15: distribute.Distribute.AddVideoJob:input_type -> distribute.AddVideoJobRequest
	13, // 16: distribute.Distribute.ListConvertCnf:input_type -> distribute.ListConvertCnfRequest
	15, // 17: distribute.Distribute.AddConvertCnf:input_type -> distribute.AddConvertCnfRequest
	2,  // 18: distribute.Distribute.GetVideoJob:output_type -> distribute.GetVideoJobResponse
	4,  // 19: distribute.Distribute.SetVideoJobResult:output_type -> distribute.SetVideoJobResultResponse
	10, // 20: distribute.Distribute.QueryVideoJob:output_type -> distribute.QueryVideoJobResponse
	12, // 21: distribute.Distribute.AddVideoJob:output_type -> distribute.AddVideoJobResponse
	14, // 22: distribute.Distribute.ListConvertCnf:output_type -> distribute.ListConvertCnfResponse
	16, // 23: distribute.Distribute.AddConvertCnf:output_type -> distribute.AddConvertCnfResponse
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_distribute_proto_init() }
func file_distribute_proto_init() {
	if File_distribute_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_distribute_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVideoJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distribute_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVideoJobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distribute_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetVideoJobResultRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distribute_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetVideoJobResultResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distribute_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoJob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distribute_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConvertCnf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distribute_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KwArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distribute_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Page); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distribute_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryVideoJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distribute_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryVideoJobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distribute_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddVideoJobRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distribute_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddVideoJobResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distribute_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListConvertCnfRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distribute_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListConvertCnfResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distribute_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddConvertCnfRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_distribute_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddConvertCnfResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_distribute_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_distribute_proto_goTypes,
		DependencyIndexes: file_distribute_proto_depIdxs,
		EnumInfos:         file_distribute_proto_enumTypes,
		MessageInfos:      file_distribute_proto_msgTypes,
	}.Build()
	File_distribute_proto = out.File
	file_distribute_proto_rawDesc = nil
	file_distribute_proto_goTypes = nil
	file_distribute_proto_depIdxs = nil
}
